# Brewfile
# git brew bundle

tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-versions'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'puma/puma'

cask_args appdir: '~/Applications'
cask 'docker'
cask 'handbrake'
cask 'makemkv'
cask 'moom'
cask 'vlc'
cask 'github'

brew 'atomicparsley'
brew 'cheat'
brew 'ctags'
brew 'direnv'
brew 'libexif'
brew 'fzf'
brew 'gh'
brew 'git'
brew 'gpg'
brew 'iperf'
brew 'krew'
brew 'kubectx'
brew 'kubernetes-cli'
brew 'libdvdcss'
brew 'mkvtoolnix'
brew 'nvim'
brew 'puma-dev'
brew 'ripgrep'
brew 'tmux'
brew 'tree'
brew 'vim'
brew 'wget'
