#!/bin/bash
# ----------------------------------------------
# Bash Profile
# ----------------------------------------------

# Colored listings
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

# Env
export EDITOR=$HOMEBREW_PREFIX/bin/nvim

# GPG
export GPG_TTY=$(tty)

# Additional bin directories
export LATEX_BIN="$HOMEBREW_PREFIX/texlive/2013/bin/x86_64-darwin"
export DF_BIN="$HOME/.dotfiles/bin"

# Homebrew Settings
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_INSECURE_REDIRECT=1
export HOMEBREW_CASK_OPTS="--require-sha --appdir=~/Applications"

# Pathing
#
# Look in Homebrew installs first, under $HOMEBREW_PREFIX, then OSX binaries. Lastly, look in the
# custom-install directories.
PATH=$HOMEBREW_PREFIX/bin:$PATH:$LATEX_BIN:$DF_BIN
export PATH
