#!/bin/bash
# ----------------------------------------------
# Bash Profile
# ----------------------------------------------

source $HOME/.bash_private

# Colored listings
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

# Env
export DUO_PASSCODE=push
export EDITOR=/usr/local/bin/vim

# Chruby settings
source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh

# Additional bin directories
export DROPBOX_BIN="$HOME/Dropbox/bin"
export LATEX_BIN="/usr/local/texlive/2013/bin/x86_64-darwin"
export SUBLIME_BIN="~/Applications/Sublime Text.app/Contents/SharedSupport/bin"
export LO_BIN="$HOME/Applications/LibreOffice.app/Contents/MacOS"
export FOX_BIN="$HOME/Applications/Firefox.app/Contents/MacOS"
export DF_BIN="$HOME/.dotfiles/bin"

# Homebrew Settings
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_INSECURE_REDIRECT=1
export HOMEBREW_CASK_OPTS=--require-sha

# Postgres
export PG_HOME="/usr/local/var/postgres"

# Pathing
#
# Look in Homebrew installs first, under /usr/local, then OSX binaries. Lastly, look in the
# custom-install directories.
PATH=/usr/local/bin:/usr/local/sbin:/opt/npm/bin:$PATH:$DROPBOX_BIN:$LATEX_BIN:$SUBLIME_BIN:$FOX_BIN:$LO_BIN:$DF_BIN
export PATH

# Java
JAVA_HOME=$(/usr/libexec/java_home)
export JAVA_HOME

# Imagemagick
export MAGICK_TEMPORARY_PATH=/Volumes/Data/tmp
export MAGICK_TEMPDIR=/Volumes/Data/tmp

# Rails version
# export RAILS_VERSION=4.2.7
# export RAILS_VERSION=5.0.0.1

# Sufia/Hydra
LOCAL_IMPORT_DIR=~/Desktop
export LOCAL_IMPORT_DIR
#SOLR_DEVELOPMENT_PORT=8983 && export SOLR_DEVELOPMENT_PORT
#SOLR_TEST_PORT=8985 && export SOLR_TEST_PORT
FCREPO_DEVELOPMENT_PORT=8986 && export FCREPO_DEVELOPMENT_PORT
FCREPO_TEST_PORT=8986 && export FCREPO_TEST_PORT
